FROM amazon/aws-lambda-python:latest

WORKDIR /newsletter

COPY ./requirements.txt .

# Install dependencies
RUN pip install --upgrade pip
RUN pip install -r requirements.txt --target "${LAMBDA_TASK_ROOT}"

COPY ./newsletter.py ${LAMBDA_TASK_ROOT}

ENV SENDGRID_API_KEY=""

CMD ["newsletter.handler"]